# 头部菜单，title: link
menu:
  Csdn: http://blog.csdn.net/qq_33050575
  Github: https://github.com/xuweikang
  Emali: https://wickhamxu@gmail.com

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - http://link.hhtjim.com/163/5146554.mp3
  - http://link.hhtjim.com/qq/001faIUs4M2zna.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: /img/bg.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: '5eef362fa1b6829d2700'
    # 应用秘钥
    clientSecret: '040cf52be4463ca25066720d544f64acc03cc73c'
    # issue仓库名
    repo: 'blog-hexo'
    # Github名
    owner: 'xuweikang'
    # Github名
    admin: ['xuweikang']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: wickhamxu

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.ico

# rss文件
rss: atom.xml
